api:
  build: ./api
  ports:
    - 3000:3000
  volumes:
    - ./api:/go/src/github.com/EwanValentine/project/api
  links:
    - database
  environment:
    - DB_NAME=project

database:
  image: postgres:9.5
  ports:
    - 5432:5432
  volumes:
    - ./db/pg-setup.sql
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: 3x1mpl3

redis:
  image: redis:3.0.4
  ports:
   - 6379:6379
